export const ADD_DATA_CART = 'ADD_DATA_CART';
export const UPDATE_PRODUCT_COUNT_IN_CART = 'UPDATE_PRODUCT_COUNT_IN_CART';
export const DELETE_PRODUCT_COUNT_IN_CART = 'DELETE_PRODUCT_COUNT_IN_CART';
export const HIDE_SPECIAL_INFO_BLOCK = 'HIDE_SPECIAL_INFO_BLOCK';
export const ADD_DATA_TO_WISHLIST = 'ADD_DATA_TO_WISHLIST';
export const ADD_DATA_PRODUCT_ID_TO_WISHLIST =
  'ADD_DATA_PRODUCT_ID_TO_WISHLIST';
export const ADD_COUNT_APPLY_LOYALTY_POINTS = 'ADD_COUNT_APPLY_LOYALTY_POINTS';
